// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsK8vYzftCwZlsC-fCSsae3Y1RJmtYmj0',
    appId: '1:967966230694:web:0961bcb202f924ac160c67',
    messagingSenderId: '967966230694',
    projectId: 'savarun-app-b775b',
    authDomain: 'savarun-app-b775b.firebaseapp.com',
    storageBucket: 'savarun-app-b775b.firebasestorage.app',
    measurementId: 'G-0Q0VQWECQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7gADuSKnx4WOeSgwNWdbyJB3qn2RkvRY',
    appId: '1:967966230694:android:db1d19f0bea2166c160c67',
    messagingSenderId: '967966230694',
    projectId: 'savarun-app-b775b',
    storageBucket: 'savarun-app-b775b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpNOxKDUv3MEhpQ27Aku4NwM9nGOWvR_A',
    appId: '1:967966230694:ios:cd8aeabb2458a031160c67',
    messagingSenderId: '967966230694',
    projectId: 'savarun-app-b775b',
    storageBucket: 'savarun-app-b775b.firebasestorage.app',
    iosClientId: '967966230694-3tr50ib7kpnoa10d5haca7tdtqhr02lc.apps.googleusercontent.com',
    iosBundleId: 'com.savarun.savarun',
  );
}
